# Generated by Django 6.0 on 2025-12-25 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='The original research query')),
                ('final_report', models.TextField(blank=True, help_text='The final research report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_session', models.ForeignKey(blank=True, help_text='Parent research session if this is a continuation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='research.researchsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchReasoning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_plan', models.TextField(blank=True, help_text='How the query was broken down', null=True)),
                ('search_strategy', models.TextField(blank=True, help_text='Search strategy used', null=True)),
                ('source_selection', models.TextField(blank=True, help_text='Why certain sources were selected', null=True)),
                ('synthesis_approach', models.TextField(blank=True, help_text='How information was synthesized', null=True)),
                ('reasoning_steps', models.JSONField(default=list, help_text='List of reasoning steps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reasoning', to='research.researchsession')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_tokens', models.IntegerField(default=0, help_text='Total input tokens used')),
                ('output_tokens', models.IntegerField(default=0, help_text='Total output tokens used')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('cost_breakdown', models.JSONField(default=dict, help_text='Cost breakdown by step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='research.researchsession')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_text', models.TextField(help_text='Summarized research findings')),
                ('key_findings', models.JSONField(default=list, help_text='List of key findings')),
                ('sources', models.JSONField(default=list, help_text='List of sources used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='research.researchsession')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='research_documents/')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text')], max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from document', null=True)),
                ('summary', models.TextField(blank=True, help_text='Summary of document content', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research.researchsession')),
            ],
        ),
    ]
