# Generated by Django 6.0 on 2025-12-26 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchreasoning',
            name='session',
        ),
        migrations.RemoveField(
            model_name='researchsummary',
            name='session',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='session',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='final_report',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='parent_session',
        ),
        migrations.RemoveField(
            model_name='researchsession',
            name='user',
        ),
        migrations.AddField(
            model_name='researchsession',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='parent_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_researches', to='research.researchsession'),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='user_id',
            field=models.CharField(default='anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='researchsession',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ResearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('content', models.TextField(blank=True)),
                ('file_size', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('research_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research.researchsession')),
            ],
        ),
        migrations.DeleteModel(
            name='ResearchCost',
        ),
        migrations.DeleteModel(
            name='ResearchReasoning',
        ),
        migrations.DeleteModel(
            name='ResearchSummary',
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
